version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdatabase
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DATABASE_URL: postgres://username:password@db:5432/yourdatabase
      JWT_SECRET: your_jwt_secret
    depends_on:
      - db
    ports:
      - "3000:3000"
