version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: lucy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registion_platform
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DATABASE_URL: postgres://lucy:password@db:5432/registion_platform
      JWT_SECRET: jwt_secret
    depends_on:
      - db
    ports:
      - "3000:3000"
